services:
  benchmark:
    build: .
    volumes:
      - ./results:/results
    environment:
      - REPO_URL=https://github.com/JavaScript-package-manager-comparison/metacubexd.git
#      - REPO_URL=https://github.com/JavaScript-package-manager-comparison/art-design-pro
      - RUNS=1
      - WARMUP=1